project:
  type: website
  output-dir: site


website:
  title: getcensus
  site-url: https://centeronbudget.github.io/getcensus/
  repo-url: https://github.com/CenterOnBudget/getcensus/
  google-analytics: "G-76S419M6JZ"
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: false
  page-footer:
    center:
      - text: "Copyright &copy; 2025 Center on Budget and Policy Priorities"
        href: https://github.com/CenterOnBudget/getcensus/blob/master/LICENSE
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    tools:
      - icon: github
        text: "GitHub"
        href:  https://github.com/CenterOnBudget/getcensus/
    contents:
      - text: "About"
        href: index.qmd
      - getting-started.qmd
      - syntax.qmd
      - options.qmd
      - geographies.qmd
      - section: "Other Features"
        contents:
          - dialog-box.qmd
          - keywords.qmd
      - examples.qmd
      - news.qmd
      - authors.qmd

format:
  html:
    theme:
      - cosmo
      - styles.scss
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 100px
      gutter-width: 2.5em
    toc: true
    toc-location: left
    code-copy: true
    footnotes-hover: true
    callout-appearance: simple
    shift-heading-level-by: 1
    quarto-required: ">=1.4"

knitr:
  opts_chunk:
    R.options:
      knitr.kable.NA: ""

execute:
  echo: false
  message: false

editor_options:
  markdown:
    canonical: true
